feeds_migrate.importer.*:
  type: config_entity
  label: "Feeds Migrate Importer"
  mapping:
    id:
      type: string
      label: "ID"
    label:
      type: label
      label: "Label"
    source:
      type: machine_name
      label: "Migration Source"
    importPeriod:
      type: integer
      label: "Import periodicity"
    existing:
      type: integer
      label: "Existing items"
    orphans:
      type: string
      label: "Orphaned Items"
