<?php

/**
 * @file
 * feeds_migrate_ui.module
 */

/**
 * Implements hook_entity_type_alter().
 */
function feeds_migrate_ui_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Config\Entity\ConfigEntityTypeInterface $migration */
  $migration = &$entity_types['migration'];

  $migration->setFormClass('add', 'Drupal\feeds_migrate_ui\Form\MigrationForm');
  $migration->setFormClass('edit', 'Drupal\feeds_migrate_ui\Form\MigrationForm');
  $migration->setFormClass('delete', 'Drupal\feeds_migrate_ui\Form\MigrationDeleteForm');
  $migration->setFormClass('process_plugins', 'Drupal\feeds_migrate_ui\Form\MigrationProcess');

  $migration->setHandlerClass('list_builder', 'Drupal\feeds_migrate_ui\MigrationListBuilder');

  $migration->setLinkTemplate('canonical', '/admin/structure/feeds-migrate/sources/{migration}');
  $migration->setLinkTemplate('edit-form', '/admin/structure/feeds-migrate/sources/{migration}');
  $migration->setLinkTemplate('delete-form', '/admin/structure/feeds-migrate/sources/{migration}/delete');
  $migration->set('admin_permission', 'administer feeds migrate importers');
}
